### ISSUE TITLE
update public page w/security workshop

### ISSUE THREAD

**Issue by shawndwells** [RedHatGov/redhatgov.github.io#2]
Hey @dischord01 - Can you update the redhatgov.io/workshops webpage with your PR from last week?

**Comment by dischord01** [comment]
Yes, but Jarad Hocutt is going to update that today or tomorrow with the
new content from my pull request, and some fixes too.

Regards,

S. Brad Sollar

**Comment by jaredhocutt** [comment]
The redhatgov.io site has been updated. Apologies for the disconnect.

We are working out a proper pull request policy so that submissions (even from us maintainers) can be reviewed by others before being merged in. We also are working to hook this process into generating the content for the redhatgov.io site.
